---
mariadb_user: mysql
mariadb_group: mysql
mariadb_conf_file: /etc/my.cnf

mariadb_server: yes
mariadb_accepts_external_connections: yes

mariadb_runtime_root: "{{ runtime_root | default('/var/run') }}/mariadb"
mariadb_pidfile_path: "{{ mariadb_runtime_root }}/mysql.pid"
mariadb_socket_path: "{{ mariadb_runtime_root }}/mysql.sock"

mariadb_log_root: "{{ log_root | default('/var/log') }}/mariadb"
mariadb_general_log_path: "{{ mariadb_log_root }}/general.log"
mariadb_slow_query_log_path: "{{ mariadb_log_root }}/slow-query.log"
