---
- name: service | mariadb | started
  service:
    name: mariadb
    state: started
  when: ansible_virtualization_type != "docker"

- name: service | mariadb | stopped
  service:
    name: mariadb
    state: stopped
  when: ansible_virtualization_type != "docker"

- name: service | mariadb | restarted
  service:
    name: mariadb
    state: restarted
  when: ansible_virtualization_type != "docker"
