---
- name: "Directory Exists | {{ mariadb_runtime_root }}"
  file:
    state: directory
    path: "{{ mariadb_runtime_root }}"
    owner: "{{ mariadb_user }}"
    group: "{{ mariadb_group }}"
    mode: 0775
  notify: service | mariadb | stopped
  tags:
    - directory-structure
    - runtime-data
    - mariadb

- name: Configure | mariadb | datadir
  lineinfile:
    dest: "{{ mariadb_conf_file }}"
    regexp: '^datadir'
    line: 'datadir = /var/lib/mysql'

- name: Configure | mariadb | datadir
  lineinfile:
    dest: "{{ mariadb_conf_file }}"
    regexp: '^user'
    line: 'user = mysql'


- name: Configure | mariadb | pidfile
  lineinfile:
    state: present
    dest: "{{ mariadb_conf_file }}"
    regexp: '^.*pid-file'
    line: "pid-file = {{ mariadb_pidfile_path }}"
  notify: service | mariadb | reloaded
  tags:
    - pidfile
    - service

- name: Configure | mariadb | bind-address
  lineinfile:
    dest: "{{ mariadb_conf_file }}"
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
  when: mariadb_accepts_external_connections
  notify: service | mariadb | reloaded
  tags:
    - networking
