---
- name: "Directory Exists | {{ mariadb_log_root }}"
  file:
    state: directory
    path: "{{ mariadb_log_root }}"
    owner: "{{ mariadb_user }}"
    group: "{{ mariadb_group }}"
    mode: 0775
  tags:
    - directory-structure
    - logging
    - mariadb

- name: Configure | mariadb | general log
  lineinfile:
    state: present
    dest: "{{ mariadb_conf_file }}"
    regexp: '^.*general_log_file'
    line: "general_log_file = {{ mariadb_general_log_path }}"
  notify: service | mariadb | restarted
  tags:
    - configuration
    - precise-configuration
    - logging
    - mariadb

- name: "File is Writable | {{ mariadb_general_log_path }}"
  file:
    state: touch
    path: "{{ mariadb_general_log_path }}"
    owner: "{{ mariadb_user }}"
    group: "{{ mariadb_group }}"
    mode: 0664
  tags:
    - permissions
    - logging
    - mariadb

- name: Configure | mariadb | slow query log
  lineinfile:
    state: present
    dest: "{{ mariadb_conf_file }}"
    regexp: '^.*slow_query_log_file'
    line: "slow_query_log_file = {{ mariadb_slow_query_log_path }}"
  notify: service | mariadb | restarted
  tags:
    - configuration
    - precise-configuration
    - logging
    - mariadb

- name: "File is Writable | {{ mariadb_slow_query_log_path }}"
  file:
    state: touch
    path: "{{ mariadb_slow_query_log_path }}"
    owner: "{{ mariadb_user }}"
    group: "{{ mariadb_group }}"
    mode: 0664
  tags:
    - permissions
    - logging
    - mariadb
